### ISSUE TITLE
Aktualisieren

### ISSUE THREAD

**Issue by beli3ver** [csware/postfix-tls-policy#4]
Frage, wird die Liste mit den Domains noch aktualisiert?

**Comment by csware** [comment]
Ja, letzte Änderung vor vier Tagen...

**Comment by beli3ver** [comment]
Was ist den der Unterschied zwischen den beiden Listen?

**Comment by csware** [comment]
Die `tls_policy-dane´-Liste funktioniert nur, wenn ein DNSSEC fähiger DNS-Server benutzt wird und bietet höhere Sicherheit.

**Comment by beli3ver** [comment]
ok
