### ISSUE TITLE
Publish log analyzer script

### ISSUE THREAD

**Issue by PhrozenByte** [csware/postfix-tls-policy#6]
Can you please publish your log analyzer script you've used to generate the initial version of the TLS policy table? This way people don't have to re-invent the wheel again.

**Comment by csware** [comment]
I'm sorry, there is no script. This was done manually. However, there is a script which can recheck the current list - I'll publish it soon.

**Comment by csware** [comment]
Done.

**Comment by PhrozenByte** [comment]
Great, thanks @csware! :+1:
