### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by PhrozenByte** [csware/postfix-tls-policy#7]
Can you please add a LICENSE file stating under which license your scripts are published (e.g. GPL-3.0, LGPL-3.0, MPL-2.0, Apache, MIT, BSD...)

See http://stackoverflow.com/a/37895659

**Comment by csware** [comment]
The DB files already include "CC-by-sa" since the beginning.

**Comment by PhrozenByte** [comment]
I didn't even see that until you told me that this is supposed to be the license info :laughing: I recommend adding a separate `LICENSE` file with the full license text and a unambiguous license header like

```
# Copyright 2014-2018 csware
#
# This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
# <http://creativecommons.org/licenses/by-sa/4.0/>
#
# License: CC-BY-SA-4.0
```

**Comment by csware** [comment]
DOne.
