### ISSUE TITLE
vodafone.de

### ISSUE THREAD

**Issue by RealMabuse** [csware/postfix-tls-policy#9]
I just got a deferred by vodafone.de:

> Reporting-MTA: dns; mail.mymailserver.de
> X-Postfix-Queue-ID: F329A7C0194
> X-Postfix-Sender: rfc822; sender@mydomain.de
> Arrival-Date: Sat, 15 Jul 2017 14:09:21 +0200 (CEST)
> 
> Final-Recipient: rfc822; recipient.name@vodafone.de
> Original-Recipient: rfc822;recipient.name@vodafone.de
> Action: failed
> Status: 4.7.5
> Diagnostic-Code: X-Postfix; Server certificate not verified

I needed to change the vodafone entry to "encrpyt", now the message got sent.

**Comment by RealMabuse** [comment]
Hmm.. just tried to:

`posttls-finger vodafone.de`

The result looks like that:

> posttls-finger: Connected to mx002.vodafonemail.xion.oxcs.net[153.92.174.58]:25
> posttls-finger: < 220-mta-p1.oxcloud-vadesecure.net ESMTP ox1mtai02p
> posttls-finger: < 220 mta-p1.oxcloud-vadesecure.net ESMTP ox1mtai02p
> posttls-finger: > EHLO mail.mymailserver.de
> posttls-finger: < 250-mta-p1.oxcloud-vadesecure.net
> posttls-finger: < 250-PIPELINING
> posttls-finger: < 250-SIZE 30000000
> posttls-finger: < 250-ETRN
> posttls-finger: < 250-STARTTLS
> posttls-finger: < 250-ENHANCEDSTATUSCODES
> posttls-finger: < 250-8BITMIME
> posttls-finger: < 250 DSN
> posttls-finger: > STARTTLS
> posttls-finger: < 220 2.0.0 Ready to start TLS
> posttls-finger: mx002.vodafonemail.xion.oxcs.net[153.92.174.58]:25: subjectAltName: *.oxcloud-vadesecure.net
> posttls-finger: mx002.vodafonemail.xion.oxcs.net[153.92.174.58]:25: subjectAltName: oxcloud-vadesecure.net
> posttls-finger: mx002.vodafonemail.xion.oxcs.net[153.92.174.58]:25 CommonName *.oxcloud-vadesecure.net
> posttls-finger: certificate verification failed for mx002.vodafonemail.xion.oxcs.net[153.92.174.58]:25: untrusted issuer /C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
> posttls-finger: mx002.vodafonemail.xion.oxcs.net[153.92.174.58]:25: subject_CN=*.oxcloud-vadesecure.net, issuer_CN=Gandi Standard SSL CA 2, fingerprint=AC:08:46:CD:FE:98:BC:50:91:40:DE:D0:1E:79:9C:D3:CF:DB:DD:1E, pkey_fingerprint=63:E7:46:C0:A0:56:80:B6:2A:17:B2:84:C4:C7:B1:D3:80:B9:84:88
> posttls-finger: Untrusted TLS connection established to mx002.vodafonemail.xion.oxcs.net[153.92.174.58]:25: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
> posttls-finger: > EHLO mail.mymailserver.de
> posttls-finger: < 250-mta-p1.oxcloud-vadesecure.net
> posttls-finger: < 250-PIPELINING
> posttls-finger: < 250-SIZE 30000000
> posttls-finger: < 250-ETRN
> posttls-finger: < 250-ENHANCEDSTATUSCODES
> posttls-finger: < 250-8BITMIME
> posttls-finger: < 250 DSN
> posttls-finger: > QUIT
> posttls-finger: < 221 2.0.0 Bye

Does that mean "secure" is okay, but "match" needs to be changed to ... hmm.. to what value?

**Comment by csware** [comment]
You need to pass a certificate store to `posttls-finger` such as `-P /etc/ssl/certs`

**Comment by csware** [comment]
Thank you for this hint.

**Comment by RealMabuse** [comment]
Okay.. I tried to do so:

`posttls-finger vodafone.de -P /etc/ssl/certs`
`posttls-finger vodafone.de -P /etc/dehydrated/certs/mymailserver.de`

Both gave exactly the same result.

**Comment by csware** [comment]
It depends where your root certificates are localted - also it need to be `posttls-finger -P /etc/ssl/certs vodafone.de` (order matters). If you see "trusted" you can use secure, otherwise you can just enforce encryption.

**Comment by RealMabuse** [comment]
Welcome back!
You need to change the "arcor.de" domain too... They use the same MTA as vodafone.de:

> posttls-finger arcor.de -P /etc/ssl/certs
> posttls-finger: Connected to mx001.vodafonemail.xion.oxcs.net[153.92.174.59]:25
> posttls-finger: < 220 mta-p1.oxcloud-vadesecure.net ESMTP ox1mtai03p
> posttls-finger: > EHLO ....
> posttls-finger: < 250-mta-p1.oxcloud-vadesecure.net
> ...
> posttls-finger: < 220 2.0.0 Ready to start TLS
> posttls-finger: mx001.vodafonemail.xion.oxcs.net[153.92.174.59]:25: subjectAltName: *.oxcloud-vadesecure.net
> posttls-finger: mx001.vodafonemail.xion.oxcs.net[153.92.174.59]:25: subjectAltName: oxcloud-vadesecure.net
> posttls-finger: mx001.vodafonemail.xion.oxcs.net[153.92.174.59]:25 CommonName *.oxcloud-vadesecure.net
> posttls-finger: certificate verification failed for mx001.vodafonemail.xion.oxcs.net[153.92.174.59]:25: untrusted issuer /C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
> posttls-finger: mx001.vodafonemail.xion.oxcs.net[153.92.174.59]:25: subject_CN=*.oxcloud-vadesecure.net, issuer_CN=Gandi Standard SSL CA 2, fingerprint=AC:08:46:CD:FE:98:BC:50:91:40:DE:D0:1E:79:9C:D3:CF:DB:DD:1E, pkey_fingerprint=63:E7:46:C0:A0:56:80:B6:2A:17:B2:84:C4:C7:B1:D3:80:B9:84:88
> posttls-finger: Untrusted TLS connection established to mx001.vodafonemail.xion.oxcs.net[153.92.174.59]:25: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
> posttls-finger: > EHLO ...
> posttls-finger: < 250-mta-p1.oxcloud-vadesecure.net
> ...

**Comment by csware** [comment]
@RealMabuse See https://github.com/csware/postfix-tls-policy/commit/85f4606810970d5487895f95f99df83bc15846ad, I committed arcor.de a few minutes after I closed this issue.
